name: Run tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Run tests
        run: bun test --coverage --coverage-reporter=lcov --coverage-reporter=text

      - uses: actions/upload-artifact@v4
        with:
          name: lcov.info
          path: coverage/lcov.info

      - name: Get Sonar coverage
        id: get-sonar-coverage
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          organization=$(grep 'sonar.organization=' sonar-project.properties | cut -d'=' -f2)
          projectKey=$(grep 'sonar.projectKey=' sonar-project.properties | cut -d'=' -f2)
          component="${organization}_${projectKey}"
          sonar_coverage=$(curl --silent --header "Authorization: Bearer $SONAR_TOKEN" "https://sonarcloud.io/api/measures/component?component=$component&metricKeys=coverage" | jq -r '.component.measures[0].value // 0')
          echo "The Sonar coverage of $component is $sonar_coverage%."
          echo 'SONAR_COVERAGE='"$sonar_coverage" >> "$GITHUB_OUTPUT"

      - name: Validate test coverage
        env:
          SONAR_COVERAGE: ${{ steps.get-sonar-coverage.outputs.SONAR_COVERAGE }}
        run: |
          coverage=$(yarn nyc report --reporter=text-summary | grep 'Lines' | awk '{gsub(/%/, ""); print $3}')
          if [ -z "$coverage" ]; then
            echo "::error::Could not retrieve test coverage."
            exit 1
          fi
          if (( $(echo "$coverage < $SONAR_COVERAGE" | bc -l) )); then
            echo "::error::Quality gate failed for test coverage. Current test coverage is $coverage%, please increase coverage to at least $SONAR_COVERAGE%."
            exit 1
          else
            echo "Test coverage is $coverage%. Quality gate passed."
          fi

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
